%YAML 1.1
---
# Keep the includes first to illustrate that definitions that everything that
# follows override included definitions.
include:
  # Only run for branches and tags
  # https://docs.gitlab.com/ee/ci/yaml/#workflowrules-templates
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - file: /ci/default.yml
    project: ModioAB/CI
    ref: main

default:
  image: $PYTHON_IMAGE

  before_script:
    - uname -a
    - pip3 install .[testing]

aiozabbix:check:
  script:
    - flake8 aiozabbix/

aiozabbix:test:
  script:
    - pytest --cov=aiozabbix
...
